# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeosimulationLandChanges
                                 A QGIS plugin
 This plugin is a tool used in spatial modeling to predict changes in land cover or land use
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-13
        copyright            : (C) 2024 by Magister Teknik Geodesi dan Geomatika FITB - ITB
        email                : tedyselan@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeosimulationLandChanges class from file GeosimulationLandChanges.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geosimulation_land_changes import GeosimulationLandChanges
    return GeosimulationLandChanges(iface)
